### ISSUE TITLE
--teachonly fails when messages are too large to be processed (error 98)

### ISSUE THREAD

**Issue by gcarret** [isbg/isbg#104]
Hi, and thank you for this very useful piece of software.

I just got this error when trying to train Spamassassin with the --teachonly option.

```
 isbg --imaphost myserver --imapuser mylogin --spaminbox INBOX.Spam --teachonly --learnspambox INBOX.Spam
9 is too big (spamc return code 98)
/home/user/.local/lib/python2.7/site-packages/isbg/imaputils.py:108: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  if mail.as_string() in ['', '\n']:
3 is too big (spamc return code 98)
12/14 spams learned
Traceback (most recent call last):
  File "/usr/local/bin/isbg", line 11, in <module>
    load_entry_point('isbg==2.1.3', 'console_scripts', 'isbg')()
  File "/home/user/.local/lib/python2.7/site-packages/isbg/__main__.py", line 262, in main
    return sbg.do_isbg()  # return the exit code.
  File "/home/user/.local/lib/python2.7/site-packages/isbg/isbg.py", line 600, in do_isbg
    proc = self.do_spamassassin()
  File "/home/user/.local/lib/python2.7/site-packages/isbg/isbg.py", line 540, in do_spamassassin
    return proc
UnboundLocalError: local variable 'proc' referenced before assignment
```
(Python 2.7.13 on Debian 9)

By looking at the code of isbg.py, the proc variable is defined on line 521, but only in absence of the --teachonly option. 

Therefore the return statement on line 540 fails.

**Comment by baldurmen** [comment]
Hi!
Thanks for reporting this bug. Sadly, Python 2 is not supported anymore. Can you try with Python 3 and see if you get the same error.

To debug, I'll also need the version of isbg you are using.

**Comment by Cetheus** [comment]
Hi baldurmen, I ran into the same Error.
As I recently installed isbg, it shows the following Version:
isbg_v2.1.3, from: /usr/local/lib/python2.7/dist-packages/isbg-2.1.3-py2.7.egg/isbg/__main__.pyc

As I'm new to python, how can I change settings to run isbg with python3?

**Comment by baldurmen** [comment]
If you are installing ISBG via pip, on Debian you will need to use the `python3-pip` package. You can then run `pip3 install isbg` and ISBG should be installed for python3.

Make sure you delete the previous version before doing that though.

If you are using virtualenv, you can follow the procedure listed here: https://stackoverflow.com/questions/10763440/how-to-install-python3-version-of-package-via-pip-on-ubuntu

**Comment by gcarret** [comment]
Same error with python 3.5.3, isbg 2.1.3 :

```
$ python3 -m isbg --imaphost myhost--imapuser myuser --spaminbox INBOX.Spam --teachonly --learnspambox INBOX.Spam --learnhambox INBOX.Ham --maxsize 500000 --partialrun 0

718 is too big (spamc return code 98)
0/6 spams learned
0/0 hams learned
Traceback (most recent call last):
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/isbg/__main__.py", line 272, in <module>
    isbgret = main()  # pylint: disable=invalid-name
  File "/usr/local/lib/python3.5/dist-packages/isbg/__main__.py", line 262, in main
    return sbg.do_isbg()  # return the exit code.
  File "/usr/local/lib/python3.5/dist-packages/isbg/isbg.py", line 600, in do_isbg
    proc = self.do_spamassassin()
  File "/usr/local/lib/python3.5/dist-packages/isbg/isbg.py", line 540, in do_spamassassin
    return proc
UnboundLocalError: local variable 'proc' referenced before assignment
```

**Comment by baldurmen** [comment]
Thanks for confirming it's the same on python3. I'll try to fix this as soon as possible.

**Comment by Cetheus** [comment]
Yes, I can confirm to, that it happens. I installed it via pip3:

```
1821 is too big (spamc return code 98)
1809 is too big (spamc return code 98)
1808 is too big (spamc return code 98)
47/50 spams learned
Traceback (most recent call last):
  File "./isbg", line 11, in <module>
    sys.exit(main())
  File "/home/pi/.local/lib/python3.5/site-packages/isbg/__main__.py", line 262, in main
    return sbg.do_isbg()  # return the exit code.
  File "/home/pi/.local/lib/python3.5/site-packages/isbg/isbg.py", line 600, in do_isbg
    proc = self.do_spamassassin()
  File "/home/pi/.local/lib/python3.5/site-packages/isbg/isbg.py", line 540, in do_spamassassin
    return proc
UnboundLocalError: local variable 'proc' referenced before assignment


pi:~/.local/bin $ ./isbg --version
isbg_v2.1.3, from: /home/pi/.local/lib/python3.5/site-packages/isbg/__main__.py

License GPLv3: GNU GPL version 3 https://gnu.org/licenses/gpl.html

This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
```

**Comment by baldurmen** [comment]
Definitely a bug and it will eventually get fixed, but in the mean time, you can pass the `–maxsize numbytes` argument to have `spamc` process large messages. The default is `120000` and the max is 256MB (`256000000` bytes)

**Comment by Cetheus** [comment]
What value do you suggest? My Provider allows Mails up to 50 MB. 
The question is, should I configure some value above that 50 MB?

**Comment by xpunkt** [comment]
If postfix change this old default i would not care anymore, i see Client 
like to find places to upload more data eath Day it's still not a filestorage


Benny

**Comment by Mkamaro** [comment]
> Definitely a bug and it will eventually get fixed, but in the mean time, you can pass the `–maxsize numbytes` argument to have `spamc` process large messages. The default is `120000` bytes (0.12MB) and the max is `256000000` bytes (256MB).

Hello,
I don't understand the "maxsize" option in this context. I have only one Spam whith 2,1 kb in my spamfolder and I tried:
`isbg --imaphost *** --imapuser *** --teachonly --learnspambox INBOX.Spam --spamc --maxsize 20000` 
or
`isbg --imaphost *** --imapuser *** --teachonly --learnspambox INBOX.Spam --spamc --maxsize 2000000`
and I tried the same without the "spamc" option and / or without the "maxsize" option
Every time i get this error:
`  File "/usr/local/bin/isbg", line 11, in <module>`
`    sys.exit(main())`
`  File "/usr/local/lib/python3.5/dist-packages/isbg/__main__.py", line 262, in main`
`    return sbg.do_isbg()  # return the exit code.`
`  File "/usr/local/lib/python3.5/dist-packages/isbg/isbg.py", line 599, in do_isbg`
`    proc = self.do_spamassassin()`
`  File "/usr/local/lib/python3.5/dist-packages/isbg/isbg.py", line 539, in do_spamassassin`
`    return proc`
`UnboundLocalError: local variable 'proc' referenced before assignment`

so I think --teachonly fails every time, independently of the size of messages?

Thank You

**Comment by aeonsablaze** [comment]
I am also seeing this behaviour regardless of message size.

**Comment by baldurmen** [comment]
Fixed!
