### ISSUE TITLE
--imaplist fails

### ISSUE THREAD

**Issue by Mkamaro** [isbg/isbg#107]
After installing with pip3 I tried:
`isbg --imaphost <myimahost> --imapuser <myimapuser> --imaplist` 
and got this error:

`IMAP password for <myimapuser>@<myimaphost>: ` 
`Traceback (most recent call last):` 
`  File "/usr/local/bin/isbg", line 11, in <module>` 
`    sys.exit(main())` 
`  File "/usr/local/lib/python3.5/dist-packages/isbg/__main__.py", line 262, in main` 
`    return sbg.do_isbg()  # return the exit code.` 
`  File "/usr/local/lib/python3.5/dist-packages/isbg/isbg.py", line 597, in do_isbg` 
`    self.do_list_imap()` 
`  File "/usr/local/lib/python3.5/dist-packages/isbg/isbg.py", line 479, in do_list_imap` 
`    dirlist = str([x.decode() for x in imap_list[1]])` 
`  File "/usr/local/lib/python3.5/dist-packages/isbg/isbg.py", line 479, in <listcomp>` 
`    dirlist = str([x.decode() for x in imap_list[1]]` 
`AttributeError: 'str' object has no attribute 'decode'` 

whats wrong?
Thank you

**Comment by baldurmen** [comment]
I can indeed reproduce this with 2.1.3. I'll try to fix it and write tests for `--imaplist` for the 2.1.4 release.

**Comment by baldurmen** [comment]
@Mkamaro you can try to apply the patch in #108 if you want, but this should be merged and made in a release soon.

**Comment by Mkamaro** [comment]
@baldurmen thank you!
I will try it in the days of next week
