### ISSUE TITLE
unclear documentation

### ISSUE THREAD

**Issue by vboehm** [isbg/isbg#110]
I have been using isbg for (much) more than a year and everything works fine. 
Until a month ago or so I used version 0.99 on Debian Buster. I don't know 
any more from where I got this version and how I installed it.

I started it by cron with

```
/usr/local/bin/isbg.py --imaphost <myProvider> --imapuser <myUser> \
    --spaminbox <mySpamFolder> --flag --delete --nostats
```

Then - after an upgrade of _openssl_ some days ago I think - nothing worked any more 
because _openssl_ refused to accept the ancient certificate of my provider. 
I took the oportunity to upgrade to a recent Version (2.1.3) of isbg.

Since you don't mention anywhere if isbg is written for python2, python3 or 
both, I tried to install with _pip3_ it on python3, which is the version I 
normally use for my programs. The installation worked fine and isbg seemed 
to work. Only when I tried

```
python3 -m isbg --nossl --imaphost <myProvider> --imapuser <myUser> --imaplist
```

I got

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.6/dist-packages/isbg/__main__.py", line 272, in <module>
    isbgret = main()  # pylint: disable=invalid-name
  File "/usr/local/lib/python3.6/dist-packages/isbg/__main__.py", line 262, in main
    return sbg.do_isbg()  # return the exit code.
  File "/usr/local/lib/python3.6/dist-packages/isbg/isbg.py", line 597, in do_isbg
    self.do_list_imap()
  File "/usr/local/lib/python3.6/dist-packages/isbg/isbg.py", line 479, in do_list_imap
    dirlist = str([x.decode() for x in imap_list[1]])
  File "/usr/local/lib/python3.6/dist-packages/isbg/isbg.py", line 479, in <listcomp>
    dirlist = str([x.decode() for x in imap_list[1]])
AttributeError: 'str' object has no attribute 'decode'
```

From that I gathered, that isbg is more for python2 than for python3 and 
installed it (with _pip_) on python2.

Now I'm fighting with the switches (old and new ones [`--deletehigherthan`
looks promising]).

My old commandline (see above) doesn't work any more. It dies with

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/vb/.local/lib/python2.7/site-packages/isbg/__main__.py", line 272, in <module>
    isbgret = main()  # pylint: disable=invalid-name
  File "/home/vb/.local/lib/python2.7/site-packages/isbg/__main__.py", line 262, in main
    return sbg.do_isbg()  # return the exit code.
  File "/home/vb/.local/lib/python2.7/site-packages/isbg/isbg.py", line 600, in do_isbg
    proc = self.do_spamassassin()
  File "/home/vb/.local/lib/python2.7/site-packages/isbg/isbg.py", line 521, in do_spamassassin
    proc = sa.process_inbox(origpastuids)
  File "/home/vb/.local/lib/python2.7/site-packages/isbg/spamproc.py", line 521, in process_inbox
    imaputils.imapflags(self.spamflags))
  File "/home/vb/.local/lib/python2.7/site-packages/isbg/imaputils.py", line 180, in func_wrapper
    res = func(cls, *args, **kwargs)
  File "/home/vb/.local/lib/python2.7/site-packages/isbg/imaputils.py", line 172, in func_wrapper
    return utils.get_ascii_or_value(func(cls, *args, **kwargs))
  File "/home/vb/.local/lib/python2.7/site-packages/isbg/imaputils.py", line 266, in uid
    return self.imap.uid(command, *args)
  File "/usr/lib/python2.7/imaplib.py", line 776, in uid
    typ, dat = self._simple_command(name, command, *args)
  File "/usr/lib/python2.7/imaplib.py", line 1091, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python2.7/imaplib.py", line 921, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: UID command error: BAD ['Invalid system flag \\FLAGGED,\\DELETED']
```

and the SPAM-files are **copied** to the SPAM-folder. 

If I use no other switches than `--nossl`, `--imaphost`, `--imapuser` and
 `--spaminbox`,  there are no errors but the result is the same:
The SPAM-files are copied to the SPAM-folder and remain in the INBOX. 

If I use only `--delete` there are no errors but the result is the same:
The SPAM-files are copied to the SPAM-folder and remain in the INBOX. 

If I use only `--flag` there are no errors but the result is the same:
The SPAM-files are copied to the SPAM-folder and remain in the INBOX. 

Until now I have the following questions which are not answered by your
documentation (neither GitHub nor ReadTheDocs nor man page).

  - What versions of python should be able to run isbg? Python2 or 
    Python3 or both?
  
  - By what switches can I accomplish the following SPAM-handling?
      - Hard SPAM (rated 15 or higher) is deleted and expunged
      - Soft SPAM (rated between 5 and 15) is <u>moved</u> to the SPAM-folder
      - Other mail is untouched

  - What does the switch `--flag` do? First I thought it would set the 
    SPAM-flag, but neither the originals in the INBOX nor the copies in 
    the SPAM-folder have a SPAM-flag after processing.
    
  - Is there a switch or environment variable or anything so I can tell
    the program not to insist on the newest ssl-features. Now I must use
    `--nossl` which is much worse than an old cipher or certificate.
    
My standard mailer is Thunderbird (60.3.1 (64-bit)) and my provisers IMAP 
server says `* OK Dovecot ready.`

Do you have any suggestions resolving my problem?
    
regard  Volker

**Comment by baldurmen** [comment]
Hi!

> What versions of python should be able to run isbg? Python2 or
Python3 or both?

ISBG is indeed a python3 program. I agree this could be made clearer in the docs. I've opened an issue #111 to track this, but feel free to submit a pull request if you have time.

> The installation worked fine and isbg seemed
> to work. Only when I tried
> 
> python3 -m isbg --nossl --imaphost <myProvider> --imapuser <myUser> --imaplist
> 
> I got
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
>     "__main__", mod_spec)
>   File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
>     exec(code, run_globals)
>   File "/usr/local/lib/python3.6/dist-packages/isbg/__main__.py", line 272, in <module>
>     isbgret = main()  # pylint: disable=invalid-name
>   File "/usr/local/lib/python3.6/dist-packages/isbg/__main__.py", line 262, in main
>     return sbg.do_isbg()  # return the exit code.
>   File "/usr/local/lib/python3.6/dist-packages/isbg/isbg.py", line 597, in do_isbg
>     self.do_list_imap()
>   File "/usr/local/lib/python3.6/dist-packages/isbg/isbg.py", line 479, in do_list_imap
>     dirlist = str([x.decode() for x in imap_list[1]])
>   File "/usr/local/lib/python3.6/dist-packages/isbg/isbg.py", line 479, in <listcomp>
>     dirlist = str([x.decode() for x in imap_list[1]])
> AttributeError: 'str' object has no attribute 'decode'
> ```

The `--imaplist` bug you encountered is a known bug (#107). The patch hasn't been merged yet, but there is a working Pull Request to fix that (#108).

> By what switches can I accomplish the following SPAM-handling?
> 
>     Hard SPAM (rated 15 or higher) is deleted and expunged
>     Soft SPAM (rated between 5 and 15) is moved to the SPAM-folder
>     Other mail is untouched

As far as I know, Spamassassin does not make a difference between levels of spam. I don't really see a way to do that with ISBG either.

> What does the switch --flag do? First I thought it would set the
> SPAM-flag, but neither the originals in the INBOX nor the copies in
> the SPAM-folder have a SPAM-flag after processing.

Also a known bug (#40) that needs to be fixed. More details on this [here](https://github.com/isbg/isbg/issues/40#issuecomment-444170037).

> Is there a switch or environment variable or anything so I can tell
> the program not to insist on the newest ssl-features. Now I must use
> --nossl which is much worse than an old cipher or certificate.

No, there is no way. As I think it's important for people to use TLS when connecting to their IMAP provider, I have no plan to add that either.
