### ISSUE TITLE
No -s size flag for spamc

### ISSUE THREAD

**Issue by andreasg123** [isbg/isbg#117]
I couldn't find a way to specify additional options for invoking `spamc`. Without `-s size`, `spamc` refuses to process messages larger than 500 KB. I would like to set `maxsize` to 3 MB because I sometimes receive large spam messages.

**Comment by baldurmen** [comment]
Hi!

I'm not sure I understand the issue you are having. I assume you are using the `--spamc` option to use spamc instead of the spamassassin binary.

Regardless, the `--maxsize` option should work. Isn't it the case?

**Comment by andreasg123** [comment]
`--maxsize` determines which messages to pass to `spamc`. Without a `-s` option, [`spamc` will only forward messages up to 500 KB to `spamd`](http://linux.fm4dd.com/en/man1/spamc.htm). To check messages larger than 500 KB for spam, both the `--maxsize` option and the `-s` option for `spamc` as to be set.

The value of `--maxsize` could just be passed on to the `-s` option of `spamc`. Alternatively, that option could be set to the maximum possible value (256 MB), because `isbg` would never give it anything larger than `--maxsize`.

**Comment by baldurmen** [comment]
Indeed, thanks for reporting this! I like the fix you propose too. Checkout out PR #118 ! From my tests, it fixes the problem.
