### ISSUE TITLE
Runtime error: local variable "spamassassin_result" referenced before assignment

### ISSUE THREAD

**Issue by vicchi** [isbg/isbg#127]
Hardware: Raspberry Pi, Model B, Rev 1
OS: Raspbian 9.11 (stretch)
Python version: 3.5.3
Spamassassin version: 3.4.2 (Perl 5.24.1)
isbg version: 2.1.5

When running `isbg` from the shell, the following error occurs:

```
$ isbg --verbose-mails --imaphost [redacted] --imapuser [redacted] --imapport 993 --spaminbox "INBOX.Junk" --dryrun
Faking spam mail
Traceback (most recent call last):
  File "/usr/local/bin/isbg", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/isbg/__main__.py", line 262, in main
    return sbg.do_isbg()  # return the exit code.
  File "/usr/local/lib/python3.5/dist-packages/isbg/isbg.py", line 600, in do_isbg
    proc = self.do_spamassassin()
  File "/usr/local/lib/python3.5/dist-packages/isbg/isbg.py", line 521, in do_spamassassin
    proc = sa.process_inbox(origpastuids)
  File "/usr/local/lib/python3.5/dist-packages/isbg/spamproc.py", line 478, in process_inbox
    if not self._process_spam(uid, score, mail, spamdeletelist, code, spamassassin_result):
UnboundLocalError: local variable 'spamassassin_result' referenced before assignment
```

I can't find any references to this either via Google searching or in this repo's issues.

Any and all help and suggestions welcome.

**Comment by vicchi** [comment]
Some further research suggests this issue is also present in v2.1.4 but _not_ in v2.1.3 ...

```
$ sudo pip3 uninstall isbg
$ sudo pip3 install 'isbg==2.1.3'
$ $ isbg --verbose-mails --imaphost [redacted] --imapuser [redacted] --imapport 993 --spaminbox "INBOX.Junk" --dryrun
Faking spam mail
Skipping report because of --dryrun
Faking ham mail
Faking ham mail
Faking ham mail
Faking ham mail
Faking ham mail
Skipping labelling/expunging of mails  because of --dryrun
1 spams found in 50 messages
0/1 was automatically deleted
```

**Comment by baldurmen** [comment]
Hi! Thanks for reporting this bug. I'm able to reproduce it and it has to do with the `--dryrun` option. Without it you should be able to run 2.1.5 without problems.

I'll push a fix for this when I'll have time to look at the code responsible for this bug.

**Comment by vicchi** [comment]
@baldurmen Thank you! I'm coming across more of these `Unbound: local variable xxx referenced before assignment` bugs I'm afraid ... do you want them raised as separate issues?

**Comment by baldurmen** [comment]
yes please.

**Comment by vicchi** [comment]
@baldurmen Just opened #129 for this. Thank you
