### ISSUE TITLE
Runtime error: local variable "proc" referenced before assignment, when using --teachonly

### ISSUE THREAD

**Issue by vicchi** [isbg/isbg#129]
As per #127 in terms of environment and versions ...

```
$ isbg --verbose-mails --imaphost [redacted] --imapuser [redacted] --imapport 993 --spaminbox "INBOX.Spam" --learnspambox "INBOX.Junk" --teachonly
50/50 spams learned
Traceback (most recent call last):
  File "/usr/local/bin/isbg", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/isbg/__main__.py", line 262, in main
    return sbg.do_isbg()  # return the exit code.
  File "/usr/local/lib/python3.5/dist-packages/isbg/isbg.py", line 600, in do_isbg
    proc = self.do_spamassassin()
  File "/usr/local/lib/python3.5/dist-packages/isbg/isbg.py", line 540, in do_spamassassin
    return proc
UnboundLocalError: local variable 'proc' referenced before assignment
```

**Comment by baldurmen** [comment]
Thanks for reporting this,

I am not able to reproduce this error on my test systems. I even switched to python 3.5.3 to see if that made a difference.

Something is working right though, since you are getting `50/50 spams learned`.

Could you run the same command with the `--verbose` option (you can drop the `--verbose-mails` one) and post the full result here?

I note that the `spaminbox` and the `learnspambox` you are using are different. Is that by choice? Could I also get a run with `--imaplist`?

**Comment by vicchi** [comment]
I am not able to reproduce this error on my test systems. I even switched to python 3.5.3 to see if that made a difference.

Something is working right though, since you are getting 50/50 spams learned.

> Could you run the same command with the --verbose option (you can drop the --verbose-mails one) and post the full result here?

Turns out I was still running 2.1.3, so after an upgrade I now get ..

```
$ isbg --verbose --imaphost [redacted] --imapuser [redacted] --imapport 993  --spaminbox "INBOX.Spam" --learnspambox "INBOX.Junk" --teachonly
Lock file is /home/pi/.cache/isbg/lock
Trackfile starts with /home/pi/.cache/isbg/trackfe042b40f3b3aa9a5645544209fa9464
Password file is /home/pi/.cache/isbg/.isbg-fe042b40f3b3aa9a5645544209fa9464
SpamFlags are []
Successfully read password file
('cabability',) = ('OK', ['IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN'])
Server capabilities: ['IMAP4rev1 SASL-IR LOGIN-REFERRALS ID ENABLE IDLE NAMESPACE LITERAL+ AUTH=PLAIN AUTH=LOGIN']
('login', 'gary+vicchi.org', 'xxxxxxxx') = ('OK', ['Logged in'])
Teach spam to SA from: INBOX.Junk
('select', 'INBOX.Junk') = ('OK', ['103'])
('uid SEARCH', (None, 'ALL')) = ('OK', ["'23762 23763 23764 23765 23766 23767 23768 23769 23770 23771 23772 23773 23774 23775 23776 23777 23778 23779 23780 23781 23782 23783 23784 …"])
Writing pastuids for folder spam: 103 origpastuids, newpastuids: []
0/0 spams learned
('logout',) = ('BYE', ['Logging out'])
```

> I note that the spaminbox and the learnspambox you are using are different. Is that by choice?

Some context might help here ...

My mail client of choice of the native macOS `Mail.app` and my main personal mail account is getting _hammered_ with spam which my mail client's junk filtering just can't cope with.

As I had a spare Raspberry Pi I put this on my LAN with `isbg` and `spamassassin` installed with the intention of running `isbg` as a `cron` job every 10 minutes or so, which would then reflect spam filtering on my laptop and on my iPhone's native mail client.

My first few passes were disappointing, no spam was detected but with quite a few false positives. So I looked into training `spamassassin` with mails which I'd identified as spam and which had been moved into `INBOX.Junk` by manually flagging them as Junk and allowing `Mail.app` to move them into that folder.

To leave my Inbox untouched, I've been trying to use `--teachonly` learn what I class as spam, in effect saying "here's a folder called Junk which is full of spam, learn from this folder and put what `isbg` and `spamassassin` thinks is spam into another folder called Spam so I can guage progress before letting it loose on my Inbox".

Does that make sense? If I'm going about this the wrong way please let me know!

Running without `--teachonly` with 102 messages in Junk and 91 messages (already identified by `isbg`) in Spam 

```
$ isbg --imaphost [redacted] --imapuser [redacted] --imapport 993  --spaminbox "INBOX.Spam" --learnspambox "INBOX.Junk"
0/0 spams learned
28 spams found in 50 messages
0/28 was automatically deleted
```

Given that there's 102 spam messages in Junk, how can I improve the recognition rate and will running with `--partialrun=0` cause _all_ the messages to be processed?

> Could I also get a run with --imaplist?

Running with `isbg` 2.1.5 ...

```
$ isbg --imaphost [redacted] --imapuser [redacted] --imapport 993  --imaplist
INBOX
INBOX.Spam
INBOX.spam
(\HasNoChildren \UnMarked) "." "INBOX.Deleted Messages"
INBOX.Drafts
INBOX.Trash
INBOX.Sent
INBOX.Junk
INBOX.Notes
(\HasNoChildren \UnMarked \Sent) "." "INBOX.Sent Messages"
(\HasNoChildren \UnMarked) "." "INBOX.Sent Items"
INBOX.Archive
```

**Comment by baldurmen** [comment]
Thank you for your time. Looks like this wasn't a bug after all :D

> Does that make sense? If I'm going about this the wrong way please let me know!
 
Yes, that makes a lot of sense.

> Running without --teachonly with 102 messages in Junk and 91 messages (already identified by isbg) in Spam. Given that there's 102 spam messages in Junk, how can I improve the recognition rate

Getting very good spam/ham ratio with SpamAssassin takes ... a bit of time and experience and is out of the scope for this project. Here are a few quick tips though:

Know that `--teachonly` trains the Bayesian filters. Most of the time, Bayesian filters are only part of the total score SA uses to decide if an email is spam or not. Those filters will get better with time if you are careful [not to poison them](https://en.wikipedia.org/wiki/Bayesian_poisoning).

I personally use a bunch of local SA rules at work for our mail boxes. I encourage you to look at online documentation on that subject and try to tune your instance.

> will running with --partialrun=0 cause all the messages to be processed?

`--partialrun` only affects the number of emails ISBG will look at during a run. If you want ISBG not to use partial runs, you can indeed use `--partialrun=0`. Depending on how many mails you have, this can take a loooong time to run though. I personally prefer to have a more frequent cron and use partial runs.

**Comment by vicchi** [comment]
Thank you!

> I encourage you to look at online documentation on that subject and try to tune your instance.

One final question ... can you point to some entry level tuning docs so I can read up on this on the train into work tomorrow?

**Comment by baldurmen** [comment]
This is not a bad page: https://cwiki.apache.org/confluence/display/SPAMASSASSIN/WritingRules
