### ISSUE TITLE
Migrating to Gitlab

### ISSUE THREAD

**Issue by baldurmen** [isbg/isbg#131]
I really dislike Github. It's proprietary and Travis CI is __bad__.

I'd really like to move this project to a Gitlab instance, more specifically to gitlab.com. It would imply some effort to port the Travis script and change a bunch of variables, but I'm ready to do that work.

We could also use Gitlab Pages instead of relying on readthedocs.io (it isn't great).

I'd like to get people's thoughts on this. From having talked with him before, I know @duk3luk3 also prefers Gitlab over Github.

I've already created the "isbg" group on Gitlab just in case... https://gitlab.com/groups/isbg

Let's give people... 2 months to reply to this issue and tell us what they think about moving to Gitlab. If on November 19th 2019 we don't have a strong consensus here against moving to Gitlab, I'll initiate the move.

**Comment by duk3luk3** [comment]
What about `sr.ht` https://meta.sr.ht/?

**Comment by duk3luk3** [comment]
Agreed that the lack of a good build service integration is a point against Github.

**Comment by baldurmen** [comment]
I like what Drew DeVault is doing. I think he's fighting the good fight.
`sr.ht` is still very alpha though and I haven't seen any clear tool to help with the migration from Github there.

I really wouldn't mind paying for the hosting service, but I feel it's a risky move given their development stage.

Maybe in a few years? :)

**Comment by Frenzie** [comment]
As an aside, CircleCI works nicer than Travis and [GitHub Actions](https://help.github.com/en/categories/automating-your-workflow-with-github-actions) is in beta. You can even use GitLab CI with GH.

(Not trying to dissuade anyone from moving, but that "Travis is bad" thing is quite separate from GH.)

On topic, I have no strong opinion on GitHub vs. GitLab. I happily use both. But of course it's a definite pro that you can roll out your own or use an alternative hosted instance like <https://framagit.org>.

**Comment by baldurmen** [comment]
[I've given Sourcehut a go](https://veronneau.org/trying-out-sourcehut.html) and I don't think it's ready yet :)

@Frenzie I didn't know about the Gitlab CI integration on Github! I've never really liked Circle CI though, and I'm not sure I like the whole Github Actions thing either. That said, my primary reason for wanting to move is Github being proprietary.

**Comment by baldurmen** [comment]
*sight*.

I mean, come on Gitlab. [Now I'm not so sure it's the right platform anymore](https://about.gitlab.com/blog/2019/10/10/update-free-software-and-telemetry/) and I'm thinking hard about migrating to sr.ht instead...

**Comment by baldurmen** [comment]
Gitlab has done the right thing and rolled back on that decision, so I'm still planning on migrating to gitlab.com. I don't fell 100% down with it, but in my honest opinion it's still the best option ATM.

**Comment by baldurmen** [comment]
I've migrated the repository to Gitlab: https://gitlab.com/isbg/isbg

I'll make this clear in the project's header and send an email on the ML.
