### ISSUE TITLE
Add option to always write headers

### ISSUE THREAD

**Issue by Plichso** [isbg/isbg#136]
It would be great to have an option that forces the configured headers, that way we could see why a email is marked as ham and we could use the header to apply filters using thunderbird or the email providers website.

**Comment by baldurmen** [comment]
ISBG doesn't do that by default because it would mean replacing every single email in your inbox (and not just spam).

I guess it could be done, but would make runs much slower. I don't really have time to add this feature, but I'd be happy to review a patch and merge it!

**Comment by baldurmen** [comment]
isbg has been moved to Gitlab.com, please continue to follow its development there:

https://gitlab.com/isbg/isbg
