### ISSUE TITLE
`--delete` without `--deletehigherthan` does not delete spam messages

### ISSUE THREAD

**Issue by bigpresh** [isbg/isbg#137]
I ran with `--delete`, intending for mail flagged as spam to be written to my spam folder (with the report), then the original to be deleted, but got e.g.:

```
25 spams found in 50 messages
0/25 was automatically deleted
```
To me, on first reading of the docs, the above seemed perfectly reasonable, I expected spam messages to be deleted, and was surprised that they were not.

I then tried again with e.g. `--delete --deletehigherthan 4`, and got what you'd expect - mails being deleted:

```
33 spams found in 50 messages
33/33 was automatically deleted
```

**Comment by baldurmen** [comment]
Hi, thanks for reporting this.

Yes, it seems something is wrong. The combination of `--delete` and `--expunge` should remove mails, but it does not.

I've poked a bit a the code and I think it's related to mails not being added to `spamdeletelist`, but I'll have to confirm that.

**Comment by baldurmen** [comment]
isbg has been moved to Gitlab.com, please continue to follow its development there:

https://gitlab.com/isbg/isbg
