### ISSUE TITLE
Error thrown when entering a mailbox with a space in name

### ISSUE THREAD

**Issue by GabrielSerealia** [isbg/isbg#138]
I'm currently trying to use isbg with Outlook.com and it keep returning the following error. Email replaced with placeholder for obvious reasons:

> root@example:~# isbg --imaphost outlook.office365.com --imapuser user@example.com --imapinbox INBOX --spaminbox "Spam Email"
> IMAP password for user@example.com@outlook.office365.com:
> Traceback (most recent call last):
>   File "/usr/local/bin/isbg", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.6/dist-packages/isbg/__main__.py", line 262, in main
>     return sbg.do_isbg()  # return the exit code.
>   File "/usr/local/lib/python3.6/dist-packages/isbg/isbg.py", line 600, in do_isbg
>     proc = self.do_spamassassin()
>   File "/usr/local/lib/python3.6/dist-packages/isbg/isbg.py", line 517, in do_spamassassin
>     self.imap.select(self.imapsets.spaminbox, 1)
>   File "/usr/local/lib/python3.6/dist-packages/isbg/imaputils.py", line 180, in func_wrapper
>     res = func(cls, *args, **kwargs)
>   File "/usr/local/lib/python3.6/dist-packages/isbg/imaputils.py", line 172, in func_wrapper
>     return utils.get_ascii_or_value(func(cls, *args, **kwargs))
>   File "/usr/local/lib/python3.6/dist-packages/isbg/imaputils.py", line 260, in select
>     return self.imap.select(mailbox, readonly)
>   File "/usr/lib/python3.6/imaplib.py", line 745, in select
>     typ, dat = self._simple_command(name, mailbox)
>   File "/usr/lib/python3.6/imaplib.py", line 1196, in _simple_command
>     return self._command_complete(name, self._command(name, *args))
>   File "/usr/lib/python3.6/imaplib.py", line 1027, in _command_complete
>     raise self.error('%s command error: %s %s' % (name, typ, data))
> imaplib.error: EXAMINE command error: BAD [b'Command Argument Error. 12']

The IMAP structure is as follows:
> Archive
> Calendar
> Calendar/Birthdays
> (\HasNoChildren) "/" "Calendar/Canada holidays"
> Contacts
> (\HasChildren) "/" "Conversation History"
> (\HasNoChildren \Trash) "/" "Deleted Items"
> Drafts
> INBOX
> Journal
> (\HasNoChildren \Junk) "/" "Junk Email"
> Notes
> Outbox
> (\HasNoChildren \Sent) "/" "Sent Items"
> Tasks

I've been trying to get it working for the past two hours, I am able to use directories that do not contain a space in their name:
> 0 spams found in 1 messages
> 0/0 was automatically deleted

Not sure if I'm just not doing it right, all the dependencies such as **SpamAssassin**, **docopt**, **cchardet**, and **xdg** are installed along with **Python 3.6** on Ubuntu 18.

**Comment by GabrielSerealia** [comment]
I tested it again with two test folders with no spaces. When there is an email it returns this error:
> Faking spam mail
> Traceback (most recent call last):
>   File "/usr/local/bin/isbg", line 11, in <module>
>     sys.exit(main())
>   File "/usr/local/lib/python3.6/dist-packages/isbg/__main__.py", line 262, in main
>     return sbg.do_isbg()  # return the exit code.
>   File "/usr/local/lib/python3.6/dist-packages/isbg/isbg.py", line 600, in do_isbg
>     proc = self.do_spamassassin()
>   File "/usr/local/lib/python3.6/dist-packages/isbg/isbg.py", line 521, in do_spamassassin
>     proc = sa.process_inbox(origpastuids)
>   File "/usr/local/lib/python3.6/dist-packages/isbg/spamproc.py", line 478, in process_inbox
>     if not self._process_spam(uid, score, mail, spamdeletelist, code, spamassassin_result):
> UnboundLocalError: local variable 'spamassassin_result' referenced before

**Comment by baldurmen** [comment]
Hi, thanks a lot for reporting this bug!

I can confirm this bug with isbg version 2.1.5:

```
tech@test:~$ isbg --delete --expunge --imaphost ********** --imapuser ********** --imappasswd ********** --imapinbox "INBOX.Dir with spaces" --spaminbox INBOX.Spam --spamc --verbose
Lock file is /home/tech/.cache/isbg/lock
Trackfile starts with /home/tech/.cache/isbg/track064a50078b4565e8dcedb06c2a32d18d
Password file is /home/tech/.cache/isbg/.isbg-064a50078b4565e8dcedb06c2a32d18d
SpamFlags are ['\\Deleted']
('cabability',) = ('OK', ['IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN'])
Server capabilities: ['IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN']
('login', '**********', 'xxxxxxxx') = ('OK', ['Logged in'])
('select', 'INBOX.Spam', 1) = ('OK', ['898'])
Traceback (most recent call last):
  File "/usr/bin/isbg", line 11, in <module>
    load_entry_point('isbg==2.1.5', 'console_scripts', 'isbg')()
  File "/usr/lib/python3/dist-packages/isbg/__main__.py", line 262, in main
    return sbg.do_isbg()  # return the exit code.
  File "/usr/lib/python3/dist-packages/isbg/isbg.py", line 600, in do_isbg
    proc = self.do_spamassassin()
  File "/usr/lib/python3/dist-packages/isbg/isbg.py", line 519, in do_spamassassin
    uidvalidity = self.imap.get_uidvalidity(self.imapsets.inbox)
  File "/usr/lib/python3/dist-packages/isbg/imaputils.py", line 280, in get_uidvalidity
    mbstatus = self.imap.status(mailbox, '(UIDVALIDITY)')
  File "/usr/lib/python3.7/imaplib.py", line 829, in status
    typ, dat = self._simple_command(name, mailbox, names)
  File "/usr/lib/python3.7/imaplib.py", line 1196, in _simple_command
    return self._command_complete(name, self._command(name, *args))
  File "/usr/lib/python3.7/imaplib.py", line 1027, in _command_complete
    raise self.error('%s command error: %s %s' % (name, typ, data))
imaplib.error: STATUS command error: BAD [b'Error in IMAP command STATUS: Invalid arguments (0.000 + 0.000 secs).']
```
The IMAP structure on my side:

```
INBOX
(\HasNoChildren) "." "INBOX.Dir with spaces"
INBOX.Trash
INBOX.Archives
INBOX.Archives.2019
INBOX.test
INBOX.Spam
INBOX.Drafts
```

I'll try to have a look at this as soon as possible, but I can't promise anything :) Meanwhile, a dirty fix is to modify the directory's name to remove spaces.

**Comment by GabrielSerealia** [comment]
Hey thanks for replying to the issue, I had marked it as closed because I wasn't sure if this was a proper issue. I ended up using a program called imapsync to do what I wanted (Bypass Outlooks spam system that can't be disabled).

I was going to rename the folder without a space, sadly Outlook doesn't allow that :(

**Comment by baldurmen** [comment]
isbg has been moved to Gitlab.com, please continue to follow its development there:

https://gitlab.com/isbg/isbg
