### ISSUE TITLE
Marked SPAM not being moved to spam folder

### ISSUE THREAD

**Issue by rosede12** [isbg/isbg#141]
The following was added to the /etc/spamassassin/local.cf

```
rewrite_header Subject *****SPAM*****
report_contact isbg@SpamPi.net
report_hostname SpamPi.net

```
This should cause ISBG to move the marked spam to the spam folder, but not all spam gets moved, some marked spam stay's in the inbox.

Any thoughts why some marked spam email does not get moved to the spam folder?

Thank you.

Daryl

**Comment by baldurmen** [comment]
isbg has been moved to Gitlab.com, please continue to follow its development there:

https://gitlab.com/isbg/isbg
