### ISSUE TITLE
--learnthendestroy should not delete hams

### ISSUE THREAD

**Issue by baldurmen** [isbg/isbg#19]
Yep, title says it all. I decided to add this lovely option to my cron to delete accumulated spam, and guess what. No more emails...

**Comment by jankkm** [comment]
I think --learnthendestroy only relates to --learnspambox and --learnhambox. So mail in the specified hambox or spambox is deleted after feeding it through SA. If none of the learn commands are used --learnthendestroy should do nothing.
It would be interesting to know what parameters you used when you experienced this behaviour.

**Comment by baldurmen** [comment]
isbg has been moved to Gitlab.com, please continue to follow its development there:

https://gitlab.com/isbg/isbg
