### ISSUE TITLE
Please make a release

### ISSUE THREAD

**Issue by yurivict** [isbg/isbg#25]
Your last release was in 2010. Many packagers go by releases only, so all your recent changes are never seen by users.

Thanks!

**Comment by baldurmen** [comment]
I'm waiting for 1.0 to be finished to do a release... Things that I want to do are in the TODO. Help is welcome.

**Comment by baldurmen** [comment]
This done! https://github.com/isbg/isbg/releases

Sadly I did not have time to do what I wanted, but still, it was time to do a release.

**Comment by AJenbo** [comment]
Nice work guys :)
