### ISSUE TITLE
[feature request] Re-write subject with detected spam level when placing the message into 'filtered' folder

### ISSUE THREAD

**Issue by yurivict** [isbg/isbg#26]

**Comment by yurivict** [comment]
For example: "****SPAM(N.N)****". But this should be configurable.

**Comment by baldurmen** [comment]
Hmm, this can be done by modifying SpamAssassin's configuration. The exact parameter is "rewrite_header": https://spamassassin.apache.org/full/3.1.x/doc/Mail_SpamAssassin_Conf.html

I'm not convinced this needs to be an option in isbg.

**Comment by yurivict** [comment]
Ah, I see, I didn't know this.
