### ISSUE TITLE
Some messages that aren't spam are placed into 'filtered' folder

### ISSUE THREAD

**Issue by yurivict** [isbg/isbg#27]
Every once in a while I see the message that went through isbg, wasn't labeled as spam (level is lower than threshold), but still placed into filtered folder.

**Comment by baldurmen** [comment]
What do you mean by "filtered" folder?

Can your parse the complete message (with SA headers and all) and the full isbg command you run?

**Comment by yurivict** [comment]
I use the option --spaminbox filtered.

Sorry, in reality it is mislabeled by spam assassin: X-Spam-Status: No, score=1.2 required=2.0 ... (It should be Yes, not it says No, and subject isn't modified too).

I will report this to them. Sorry for bothering.

**Comment by yurivict** [comment]
I use the option --spaminbox filtered.

Spam assassin says: X-Spam-Status: No, score=1.2 required=2.0 ...

It is not a spam, but it is placed into spaminbox.

**Comment by yurivict** [comment]
````
isbg.py \
  --imaphost <hidden> \
  --imapuser yuri \
  --imapinbox Inbox \
  --imappasswd=<hidden> \
  --savepw \
  --spaminbox filtered \
  --flag --delete --expunge --ssl \
  --lockfilename $LOCK \
````

**Comment by yurivict** [comment]
I really can't understand what is happening. MY provider runs spamassassin, and then I run it with isbg. Both provider and me label subject with different tags, like ***SPAM***. But once in a while I see the message that isn't tagged in any way, and it says X-Spam-Status: No, score=1.2 required=2.0 (score<required), but when I run it manually, SpamAssassin says score is higher and it is spam. Very confusing, not sure how can this be. But it says it was checked by SA on my system though.

**Comment by baldurmen** [comment]
This is how SA manages spam score. In no way it a isbg bug. Please read SA documentation about spam sensitivity and score adjustment.

**Comment by yurivict** [comment]
But why the message that isn't spam is placed into the spaminbox? Only isbg moves messages.

**Comment by baldurmen** [comment]
isbg runs on a local SA. Your provider conf must be different than your SA conf.
