### ISSUE TITLE
I need to be able to do shorter runs

### ISSUE THREAD

**Issue by naevtamarkus** [isbg/isbg#29]
Hi,

First, thanks a lot for your wonderful tool! I have banged my head against a wall for so many hours until I found your tool.

I currently have over 6000 mails in my inbox that I need to clean up and doing a full run will take many hours; this is something that I can't simply do in one shot. The problem is that the trackfile and the deletion/expunge in the server does not happen until the very end of the operation! If I cancel the operation all reports are in the Spam folder, but the originals remain and the next run starts from the beginning. This means I will never be able to really clean my stuff.

I am going to implement a new parameter (--partialrun num) that will break the main loop once a certain number of emails have been processed. I think this should do the trick while being simple to develop and easy to understand. It might not be the ideal solution (deleting and writing to trackfile after each message is parsed) but that would be too costly for me and probably for you.

My question is whether you would be interested to see such feature into the master branch. Just let me know, and I will do the commits.

Thanks!

**Comment by baldurmen** [comment]
Humm, I do understand the issue your have. I know the code is a mess right now (working on it...), but if you submit a well-written patch that manages to break the loop in smaller pieces, I'll be glad to add it to the master branch! 50 emails at a time would be nice but you could pass it as a parameter.

**Comment by baldurmen** [comment]
Fixed by commit 906b0f66ff68f5071c16e9ddf3bf555ae816b6ff
