### ISSUE TITLE
SSL should be the default

### ISSUE THREAD

**Issue by naevtamarkus** [isbg/isbg#30]
Hi,

One can never be too paranoid... but having your password travel the internet in clear text is way too much. I think SSL should be the default protocol and not the option, in order to prevent mistakes (like I did).

May I ask: could you please turn the --ssl parameter into a --nossl parameter that does the opposite? This way the feature of not-using-ssl is there, but is only optional.

If you don't have the time I will be very happy to push it myself... but of course the code will not be backwards-compatible.

Thanks!

**Comment by baldurmen** [comment]
Your are right: I did the same (not inputting the --ssl parameter) the first time I used ISBG.

Anyway, I did the change you proposed. As for backward compatibility, I've been working on a 1.0 release and a lot of thing changed/will change, so it's not very important.

As for the ones using the dev version, well, they should read the changelog! :D
