### ISSUE TITLE
Use spamassassin instead of spamc/spamd combination

### ISSUE THREAD

**Issue by naevtamarkus** [isbg/isbg#34]
Have you considered running isbg with spamassassin (binary) as a user, without the need of spamd --allow-tell? It would simplify the installation and let the user have full control over the whole thing in case of shared/protected environments.

**Comment by naevtamarkus** [comment]
CORRECTION: this is, indeed, the case with --learnhambox and --learnspambox parameters. Normal cleanup executions actually use spamassassin instead of spamc by default unless you specify --spamc as a parameter.

**Comment by baldurmen** [comment]
I'll be in DebConf in Heidelberg in a few days and I hope to:
* have a look at this
* review the patch you submitted for the partial run
* finish version 1.0
* package ISBG for Debian

Until then I really don't have time to work on this (but thanks for your input, it really helps!)

**Comment by baldurmen** [comment]
fixed by #86

**Comment by baldurmen** [comment]
oops, the learning process is still using `spamc`. Sorry for the noise

**Comment by baldurmen** [comment]
isbg has been moved to Gitlab.com, please continue to follow its development there:

https://gitlab.com/isbg/isbg
