### ISSUE TITLE
--flag does nothing for me

### ISSUE THREAD

**Issue by optima-software** [isbg/isbg#40]
Hi to all,
this is my call

```
isbg.py --imaphost $host --imapuser $user --imappasswd $pass --delete --flag --noreport --spamc

```

Accidentialy the --flag does nothing for me. I was expecting to get the mail subject marked with ***_SPAM**_*

Thanks, best Regards
\st

**Comment by baldurmen** [comment]
... I'm not sure I understand what you mean with this bug report. Could you be a little clearer?

If you want spams marked as ***SPAM*** you have to modify spamassassin's configuration (/etc/spamassassin/local.cf)

**Comment by baldurmen** [comment]
Haa, I think I get it, my bad. Hmm, --flag is another cli option that I never used...

IMHO I should simply remove it, since it's better to configure SA directly.

**Comment by optima-software** [comment]
Yeah ok. This is a proper approach.

I have tried this, but it seems that I am failing in configuring the mess of spamasassin config files.
I found all these files: 
```
/usr/share/spamassassin/local.cf
/etc/mail/spamassassin/local.cf (/etc/spamassassin/local.cf)
/home/pi/.spamassassin/user_prefs
/root/.spamassassin/user_prefs
```
In all of them I activated
```
rewrite_header Subject *****SPAM*****
required_score 5.0
``` 
But still my subjects are not modified.
I know that this is the wrong chat, but maybe you can help with your spamassassin experience!?

**Comment by baldurmen** [comment]
I use `/etc/spamassassin/local.cf` for global config, but ~/.spamassassin/user_prefs should work just fine too.

Have you restarted SA after making the changes?

**Comment by optima-software** [comment]
Yes, sure I did restart the service.
Just for me to understand: isbg.py is feeding spamassassin with every mail from the imap account, while SA itself has no access to the imap inbox.
How can SA modify the subject than?

**Comment by baldurmen** [comment]
IBSG fowards the email to SA to be checked for against content rules
(i.e. NO ALL CAPS MESSAGES 'CAUSE IT'S NORMALLY SPAM), but also for ip
adresses and blacklisted domains.

To do so, it needs access to headers too. If you enable `rewrite_header
Subject foobar`SA simply strips the "Subject" line and rewrites it the
way you want.

SA then sdtout the whole email (headers and body) to isbg, whom replaces
the original content by it.

I can't help you more than that with SA, since this is definitely not
the place for it.

I won't close it though since the original problem has not been fixed.

**Comment by optima-software** [comment]
I do not know why, but 'rewrite_header Subject' does not work for me.
So I'll keep the --flag and wait for your fix ;-)

Thanks.

**Comment by baldurmen** [comment]
Looking back at this:

1. The option does something, it sets the `\Flagged` IMAP flag.
2. As per [RFC 3501](https://tools.ietf.org/html/rfc3501#section-2.3.2), there is no valid `\Spam` flag.
3. The option can be useful if you want to flag spam and then play with them with options like `--learnthenflag` or `--learnunflagfed`.

I still feel like this option is not used by a lot of people and adds an unnecessary layer of complexity for ISBG. As so, I think we should remove all flag related options.

**Comment by baldurmen** [comment]
Oh well, it seems those functions are important, since Gmail uses flags a lot for handling emails and we want to continue supporting it.
