### ISSUE TITLE
Create a mailing list for developpment and questions

### ISSUE THREAD

**Issue by baldurmen** [isbg/isbg#45]
https://mail.python.org looks like they have some nice mailman lists available for python projects.

**Comment by lenucksi** [comment]
I can also recommend https://gitter.Im as a discussion forum for GitHub projects. Its free and works reasonably well. Also integration is just a few clicks...

**Comment by baldurmen** [comment]
I'd prefer sticking to a traditional mailing list. Gitter does not seem to be free software either.

**Comment by baldurmen** [comment]
Just sent a mail at https://mail.python.org/ to get a list. Will keep this issue updated!

**Comment by baldurmen** [comment]
I also asked Thomas to give me admin control on the #isbg IRC channel on Freenode.

**Comment by baldurmen** [comment]
Got an answer from mail.python.org folks. We should have a working Mailmain3 list soon.
