### ISSUE TITLE
Change the license

### ISSUE THREAD

**Issue by baldurmen** [isbg/isbg#50]
The license we are using at the moment is more a lack of license than anything. This is problematic for packaging isbg into Linux distros. For example, Debian won't accept it because of the unclear license.

With a 2.0 version, I feel that I'll have the moral right to change the license Roger Binns chose, since a lot of the code will have changed by then.

I'm very fond of the GPLv3. I wonder if this should be licensed under the AGPLv3 though since one of the use cases is people offering isbg as a service.

I'd like isbg users input on this. What license do you prefer? Do you mind the (A)GPLv3?

**Comment by OzzieIsaacs** [comment]
I'd perfer the GPLv3 licence.
