### ISSUE TITLE
Stop execution (crtl+c)

### ISSUE THREAD

**Issue by heruan** [isbg/isbg#52]
Stopping execution with <kbd>CTRL</kbd>+<kbd>C</kbd> doesn't work and leaves the script in a dirty state (e.g. locks). It would be very useful to have the signal work to block a long running execution.

**Comment by baldurmen** [comment]
Hmmm, I've done that countless times and it never caused any problems to me.

Can you give me the full error trace please?

**Comment by baldurmen** [comment]
fixed in the latest version. We now have a proper Keyboard interrupt handling.
