### ISSUE TITLE
ISBG not closing after a scan

### ISSUE THREAD

**Issue by brightonguy** [isbg/isbg#55]
I have found that ISBG is not closing after completing  a scan, but still responds to ^c.
Most recently this was doing learnanddelete, all the spam box was deleted, and it seems that the script hung.

It is running on raspbian (latest), on a Pi 2.

Any thoughts please

**Comment by baldurmen** [comment]
Can I have the full command you are running? Could you run it in verbose mode and post the full trace?

**Comment by brightonguy** [comment]
Hi Louis-Philippe, how do I post the files? I keep getting a too big for 
the 'MX responsible for the recipient'. The log file and screen data is 
about 4.0M.


Mike

**Comment by brightonguy** [comment]
Sorry for the delay - I am away from home, and it is a bit tedious to get the files here. Anyway, the problem has changed slightly. ISBG is now terminating prematurely. I attach the screen output (verbose), and closing error messages.
Perhaps you would be able to help?
Many thanks Mike

[Terminal Saved Output.txt](https://github.com/isbg/isbg/files/435680/Terminal.Saved.Output.txt)

**Comment by brightonguy** [comment]
Didn't like the raw log file!
[isbg.log.zip](https://github.com/isbg/isbg/files/435683/isbg.log.zip)

**Comment by brightonguy** [comment]
my command line is 
isbg.py --imapuser jill42newsome@ambers-house.co.uk --verbose > isbg.log 
I have tweaked the python source to default to my imap server, spam bix ham box etc, to save the typing!
Thanks
Mike

**Comment by baldurmen** [comment]
fixed in the latest version.
