### ISSUE TITLE
Bulk issues / comments from first time use

### ISSUE THREAD

**Issue by internationils** [isbg/isbg#56]
Hello, I encountered several issues:
- problem with --savepw ... I would have expected that I can leave that option, and that if it finds a PW file that it uses it (instead of asking for a PW again)
- problem with --passwdfilename ... that option name is confusing: I was expecting to give it a filename that it reads the PW from.... instead it did what I expected --savepw to do
- the username@domain.com@mailserver.maildomain.com notation is VERY confusing to read, change it to username@domain.com (server: mailserver.maildomain.com) or something similar
- by default it did NOT remove the spam from the inbox (as per the docs). It left it there. THis should be more clearly documented: either default is "leave the spam and copy it" (and delete only if --delete is specified)
- a progress indicator (Processing nnn/MMM mails...) would be helpful to show when working with larger inboxes
- result info is incorrect: 12 spams found in 294 messages /// 0/12 was automatically deleted ... this is with --delete --expunge, and the messages did get deleted fro the inbox and showed up in the spambox

I think that's it for now, thanks for a great tool otherwise!
Cheers
Nils

**Comment by baldurmen** [comment]
> * problem with --savepw ... I would have expected that I can leave that option, and that if it finds a PW file that it uses it (instead of asking for a PW again)
> * problem with --passwdfilename ... that option name is confusing: I was expecting to give it a filename that it reads the PW from.... instead it did what I expected --savepw to do

The password saving features in ISBG is a mess. I personally do not use it and would advise to use a shell wrapper script instead. There are examples scripts in the repo.

> * the username@domain.com@mailserver.maildomain.com notation is VERY confusing to read, change it to username@domain.com (server: mailserver.maildomain.com) or something similar

I'm not sure I get the username issue... `--imaphost mymail.net --imapuser foobar@mydomain.net` seems clear to me for the CLI commands. Are you talking about logs?

> * by default it did NOT remove the spam from the inbox (as per the docs). It left it there. THis should be more clearly documented: either default is "leave the spam and copy it" (and delete only if --delete is specified)

The documentation states: "The default behaviour of isbg is to not make any changes your Inbox unless you specify specific command line options. Consequently you can experiment without worry at the begining."

That and the CLI help page adds: "    (Your inbox will remain untouched unless you specify --flag or --delete)"

> * a progress indicator (Processing nnn/MMM mails...) would be helpful to show when working with larger inboxes

Indeed! This would be quite easy to do when ISBG will work in loops of X messages. I've added an issue about it.

> * result info is incorrect: 12 spams found in 294 messages /// 0/12 was automatically deleted ... this is with --delete --expunge, and the messages did get deleted fro the inbox and showed up in the spambox

Maybe related to #53 ?

> I think that's it for now, thanks for a great tool otherwise!

Thanks for the feedback, it's appreciated!

**Comment by internationils** [comment]
Hi, thanks for the quick response!

Password: I can use a shell script and read the password from another file, then pass it with --imappasswd ...no problem.

For the second point, run this to see what I mean about the syntax:
```
./isbg.py --savepw --imapuser myuser@mydomain.com
IMAP password for myuser@mydomain.com@localhost:
```

Sorry, the docs are correct. Maybe it was another blog page I was reading.

The last point is related to #53, yes. I've commented in that issue... I'm not using partialrun or spamc.

I would also suggest a --quiet option, it's normal for lots for tools that may run from cron. I guess --nostats might achieve the same thing (at least in cases without failures of any kind), but a --quiet is usually an override for all informational messages.

Also, a --rescan option would be good. I was debugging spamassassin (uribl queries) and had to manually remove the .isgb-track files a few times to get it to look at old mails again.

Something else weird is that I have a mailbox reporting 900+ mails, and isbg reports having processed 700some when it finishes. This might be a Roundcube issue, not sure.

**Comment by internationils** [comment]
One more :)
- please use a ~/.isbg directory for the files. I'm checking several IMAP accounts from within one user, and that creates a mess if .isbg* files in the home directory.

**Comment by baldurmen** [comment]
Everything but the progress bar has been fixed in the latest version.

For the progress bar, see #57
