### ISSUE TITLE
Command line parameters do not work

### ISSUE THREAD

**Issue by rnaheed** [isbg/isbg#58]
Other than --help, none of the other parameters work for me.  They just display the same output as --help.  For instance:

./isbg.py --imaphost localhost

displays the usage and the options.  This is with python 2.7.5 and python-docopt 0.6.1-2.

**Comment by rnaheed** [comment]
Nevermind.  Sorry about the bug report.  I just saw that only lower versions of python are supposed.

**Comment by rnaheed** [comment]
So, it appears the issue wasn't due to newer versions of python.  I am running python 2.6.6 on a different machine and get the same result.

**Comment by Ray76** [comment]
Hey rnaheed, I ran into the same issue, I got it working when I use 
docopt version 0.5.0

Cheers

**Comment by baldurmen** [comment]
Hmm, yeah. I took for granted people would use recentish versions of docopt.

The version I use is 0.6.2, the one in Debian at the moment.
