### ISSUE TITLE
Unclear option: --delete

### ISSUE THREAD

**Issue by kuba-orlik** [isbg/isbg#64]
I have trouble understanding the meaning behind the `--delete` option. Does setting it mean that:

* the message will be copied to `spam` folder AND deleted from inbox, or 
* deleted from the server so there's no trace of it?

**Comment by baldurmen** [comment]
Sorry it took me so long to answer.

`--delete` marks your mail for deletion. I does not delete nor remove the mail from your inbox, but will mark it as spam if it is. The IMAP server will purge them, something analog to this: https://secure.php.net/manual/en/function.imap-delete.php

If you want it remove, you must specify `--expunge`. That will move the spam from the inbox to your spam folder.

Is that clearer?

**Comment by kuba-orlik** [comment]
I understand now that the `--delete` option does not delete messages, but marks them for deletion. But what does the `--expunge` option do, really? Does it:

* delete *all messages marked for deletion on the server*,
* delete only the spam messages detected in this particular run cycle, or
* move spam messages to the desired folder?

**Comment by baldurmen** [comment]
`--expunge` removes a message marked for deletion from your inbox.

Copying the spam to the spambox is done when either the `--delete` or the `--flag` params are passed.

So:

* `--delete` marks spam for deletion but does not remove it from the inbox
* `--flag` marks spam as spam but does not remove it not mark it for deletion
* `--delete` or `--flag` *copies* the spam to the inbox
* `--expunge` removes messages marked as spam from your inbox

I know it's a little confusing, but this is standard IMAP specs.
