### ISSUE TITLE
0/x spams learnt

### ISSUE THREAD

**Issue by kuba-orlik** [isbg/isbg#65]
Running

```
isbg.py --imaphost xxxxx --imapuser xxxxx --imapinbox INBOX --spaminbox Junk --learnspambox learn_spam --verbose --teachonly
```

Yields:

```
(...)
('7', 'Message was already un/learned\n')
0/7 spams learnt
```

Even though some of the messages contained in the `learn_spam` folder were brand new and never before seen by the script... Why is that so?

**Comment by duk3luk3** [comment]
"Message was already un/learned" comes straight from spamassassin. Maybe identical messages have been learned before?

**Comment by kuba-orlik** [comment]
Highly unlikely, as it always gives this message, even if there are ~20 new messages in the inbox

**Comment by baldurmen** [comment]
fixed in latest version.
