### ISSUE TITLE
Change the way track files work

### ISSUE THREAD

**Issue by baldurmen** [isbg/isbg#74]
At the moment, ISBG writes into a track file (.isbg-trackxxxxxxxx) to keep a log of the message it has read.

This is not nice since:
* it clutters you working directory
* is not efficient for large scale uses
* you can't read the md5 hashsum and know what trackfile belongs to what user account easily

I think it would be best to use something like sqlite to replace the track file behavior. It's very efficient for such light use, easily exportable and gives us some way to organise data.

**Comment by duk3luk3** [comment]
I've already changed the trackfile behaviour in v2.0 (See a64d406d2dae5b598778dfddd2ec3d37fe68bc6b and ba2514b65988041a9fe1cea1fb9bf1fd0e09b0b6). The data format is now JSON, it respects the UIDVALIDITY attribute of IMAP folders, and by default it has per-user and per-folder trackfiles (so one trackfile each for the sa inbox, the spamlearning inbox, and the hamlearning inbox).

Changing it to sqlite is a good idea.

**Comment by baldurmen** [comment]
The latest version doesn't use sqlite, but it's much more readable. I guess we can close this.
