### ISSUE TITLE
Learnham should remove spamassassin report from mailcontent

### ISSUE THREAD

**Issue by TheCasualObserver** [isbg/isbg#83]
This report is based on isbg V1.0.

During my first run with isbg some mails were falsely identified as spam.
After putting them into my learnhambox folder, they were correctly learned as ham and put back into my movehamto mailbox, however their e-mail content still contained the spamassassin spam-report.

I would have expected that the spam-report is removed during the process of identifying a mail as ham.

May I ask you to implement the feature that the spamassassin report is removed, when the mail is identified as ham.

I believe that the necessary changes should go about here: https://github.com/isbg/isbg/blob/1.00/isbg.py#L497 
And spamassassin provides the --remove-markup command line option for this functionality.

**Comment by baldurmen** [comment]
isbg has been moved to Gitlab.com, please continue to follow its development there:

https://gitlab.com/isbg/isbg
