### ISSUE TITLE
Integrate RSpamD as spam filtering system

### ISSUE THREAD

**Issue by lenucksi** [isbg/isbg#84]
Would it be possible to use [RSpamD](https://rspamd.com) as alternative to spamassasin?

**Comment by baldurmen** [comment]
I'm having trouble maintaining ISBG already, so I don't think that will be feasible.

Sorry.

**Comment by rsmuc** [comment]
I have a rough implementation of rspamd for isbg:
https://github.com/rsmuc/isbg/tree/rspamd

There are not too many changes required. @baldurmen if you are interessted in rspamd support, I can clean up the code and provide a PR.

**Comment by baldurmen** [comment]
Hi,

As I said previously, I really don't have the time and the energy to maintain another spam filtering backend for ISBG. I prefer to do only Spamassassin and do it right(ish) instead of trying to do both and risk failing.

Sorry :(
