### ISSUE TITLE
Occasional error report from spamassassin call

### ISSUE THREAD

**Issue by JohnKendrick** [isbg/isbg#90]
I see the following error from time to time...
It doesn't halt the scanning of the imap directory, but I thought you might want to know about it.

('uid fetch', u'4413', '(BODY.PEEK[])') = ['OK', [['11 (UID 4413 BODY[] {3539}', "'Return-Path: <noreply@rmg-ebusiness.com>\\r\\nDelivered-To: <john@kendrick.me.uk>\\r\\nReceived: fro..."], ')']]
Error communicating with ['spamassassin', '--exit-code']!
Traceback (most recent call last):
  File "build/bdist.linux-x86_64/egg/isbg/isbg.py", line 567, in spamassassin
    score = p.communicate(body)[0].decode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2982: ordinal not in range(128)
('uid fetch', u'4414', '(BODY.PEEK[])') = ['OK', [['12 (UID 4414 BODY[] {24451}', "'Return-Path: <notification+kr4mqebaa2rx@facebookmail.com>\\r\\nDelivered-To: <john@kendrick.me.uk>..."], ')']]
[4414] score: -6.7/5.0

**Comment by baldurmen** [comment]
Can you check if you have the same behavior if you use this branch #86 ? I know I told you to use the 2.0.0 branch, but it's a pretty substantial PR and it solves a bunch of bugs.

**Comment by baldurmen** [comment]
Well, [2.1.0](https://github.com/isbg/isbg/releases/tag/2.1.0) has just been released. Please test against that.

**Comment by baldurmen** [comment]
Hi! I'm likely to close this bug report next time I look at it if you don't report similar problems with 2.1.0.
