### ISSUE TITLE
Not keeping track of read emails

### ISSUE THREAD

**Issue by JohnKendrick** [isbg/isbg#91]
Branch 2.0.0 doesn't seem to keep track of emails which have been read and processed.

Using verbose I saw;

('uid fetch', '4413', '(BODY.PEEK[])') = ['OK', [[b'11 (UID 4413 BODY[] {3539}', "b'Return-Path: <noreply@rmg-ebusiness.com>\\r\\nDelivered-To: <john@kendrick.me.uk>\\r\\nReceived: fr..."], b')']]
[4413] score: 2.7/5.0

Writing pastuids, 0 origpastuids, newpastuids: []
0 spams found in 10 messages
0/0 was automatically deleted

At the end of a limited run.  I would have expected to see a list of newpastuids, but it is empty.
Redoing the command processes exactly the same emails.

Looking at the code on line 991 it is;
            body = self.getmessage(u, newpastuids)

getmessage appends the uids to a list using a named parameter, but the result is never passed back to the calling frame.
I therefore just added;
            newpastuids.append(u)
After the getmessage command.

This seems to result in the desired behaviour.

**Comment by baldurmen** [comment]
This is fixed in #86 .
