### ISSUE TITLE
Feature: Rewrite the subject of an e-mail

### ISSUE THREAD

**Issue by christophKi** [isbg/isbg#96]
Hello!

I would love to have an option to rewrite the subject of an e-mail if it was detected as spam. For example to add ***spam*** to the subject. In some cases I would prefer this opportunity instead of moving the detected email to an other folder or to flag it. 

Greatings
christophKi

**Comment by baldurmen** [comment]
That's a feature offered by SpamAssassin.

IRRC the option is called something like `add rewrite_subject`.

**Comment by christophKi** [comment]
I would like to rewrite the subject for mails in the inbox. 
`rewrite_header Subject ** Möglicher Betrug! **` is set in the `$HOME/.spamassassin/user_prefs` config file and working. But only for mails moved to the spam folder.

**Comment by baldurmen** [comment]
I guess you could set your spambox with `--spaminbox` to your inbox instead of a spam folder?

**Comment by baldurmen** [comment]
iSBG already has a lot of features. Sadly, we don't plan to add this one since it seems to be a very narrow use case.

**Comment by christophKi** [comment]
At GMX this is a common feature. Too bad that they are not implemented.
![gmx](https://user-images.githubusercontent.com/29779413/42291788-425b9bc0-7fce-11e8-9e21-806c56f8b824.JPG)
Translated it means: 

> Spam options for POP3 users
> 
> Select whether emails sorted out as spam should be stored in your GMX account in the Spam suspected folder or sent with the subject heading "*** GMX Spam suspected ***" as normal and thus also be available via POP3.
