### ISSUE TITLE
Feature: Send e-mail notification in crontab only on error

### ISSUE THREAD

**Issue by christophKi** [isbg/isbg#97]
Hi again!

I tried to set it up to send an e-mails from crontab only when an error comes up. 
That worked for me with `>/dev/null` at the end of the command in version 1.0.
But with 2.1 I always get the standard messages per mail everytime the script runs from crontab. 
In the crontab.example there is only an example for redirect stdout and stderr to logger. May you can give also an example for sending an e-mail, if an error comes up, otherwise redirect standard messages to the logger or to > /dev/null.

Greetings
christophKi

**Comment by baldurmen** [comment]
You can use the `--nostats` options to stop getting message like this one:

```
0 spams found in 1 messages
0/0 was automatically deleted
```
That way you can keep getting error messages by email via crontab's regular MTA feature.
