### ISSUE TITLE
--movehamto mbox - does not move the mail, it just copies it to the given folder

### ISSUE THREAD

**Issue by christophKi** [isbg/isbg#98]
The command I am using:
isbg --[host] --imapuser [user] --spaminbox Junk --passwdfilename $HOME/pw --trackfile $HOME/track --spamc --expunge --delete --lockfilename $HOME/lockfile --imapinbox Mails-NEU --learnhambox Mails-NEU --movehamto INBOX

 --learnthendestroy deletes the mail bevore it is copied to the given folder.

Greetings
christophKi

**Comment by baldurmen** [comment]
isbg has been moved to Gitlab.com, please continue to follow its development there:

https://gitlab.com/isbg/isbg
